### ISSUE TITLE
from fpdf import FPDF : missing

### ISSUE THREAD

**Issue by neso613** [akash-rajak/Real-Time-Human-Detection-Counting#5]

**Comment by akash-rajak** [comment]
Hi @neso613 , you need to install fpdf python library first
you can do it using below command
pip install fpdf
in command prompt

Try this and let me know if any error comes

**Comment by neso613** [comment]
Hi @akash-rajak 
fpdf issue is resolved but get this errror - 
`Traceback (most recent call last):
  File "main.py", line 20, in <module>
    window.iconbitmap('Images/icon.ico')
  File "/home/neha/anaconda3/envs/tf2.6/lib/python3.7/tkinter/__init__.py", line 1871, in wm_iconbitmap
    return self.tk.call('wm', 'iconbitmap', self._w, bitmap)
`

**Comment by neso613** [comment]
> there is an images folder, that images folder should in same location where main.py and persondetection.py are there, can you please check if images folder is in same location or not?

image is at same place.

**Comment by akash-rajak** [comment]
Try this and let me know what happens
just comment the line no. 20, 64, 85, 273 and 503
then run the code

**Comment by akash-rajak** [comment]
yes, with tensorflow it is slow, there is one more algorithm like YOLO with tensorflow, you can try this and it would probably solve the speed issue too
